// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.
//
// To add a suppression to this file, right-click the message in the 
// Error ListQueues, point to "Suppress Message(s)", and click 
// "In Project Suppression File".
// You do not need to add suppressions to this file manually.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Microsoft.Build.Utilities.TaskLoggingHelper.LogMessage(System.String,System.Object[])", Scope = "member", Target = "StealFocus.MSBuildExtensions.Tasks.BizTalk.BizTalkTerminateOrchestrations.#Execute()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Microsoft.Build.Utilities.TaskLoggingHelper.LogMessage(System.String,System.Object[])", Scope = "member", Target = "StealFocus.MSBuildExtensions.Tasks.BizTalk.BizTalkAddAdapter.#Execute()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Microsoft.Build.Utilities.TaskLoggingHelper.LogWarning(System.String,System.Object[])", Scope = "member", Target = "StealFocus.MSBuildExtensions.Tasks.BizTalk.BizTalkAddAdapter.#Execute()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Microsoft.Build.Utilities.TaskLoggingHelper.LogMessage(System.String,System.Object[])", Scope = "member", Target = "StealFocus.MSBuildExtensions.Tasks.BizTalk.BizTalkCleanHostQueue.#Execute()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Microsoft.Build.Utilities.TaskLoggingHelper.LogMessage(System.String,System.Object[])", Scope = "member", Target = "StealFocus.MSBuildExtensions.Tasks.BizTalk.BizTalkCreateApplication.#Execute()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Microsoft.Build.Utilities.TaskLoggingHelper.LogError(System.String,System.Object[])", Scope = "member", Target = "StealFocus.MSBuildExtensions.Tasks.BizTalk.BizTalkCreateHost.#Execute()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Microsoft.Build.Utilities.TaskLoggingHelper.LogMessage(System.String,System.Object[])", Scope = "member", Target = "StealFocus.MSBuildExtensions.Tasks.BizTalk.BizTalkCreateHost.#Execute()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Microsoft.Build.Utilities.TaskLoggingHelper.LogMessage(System.String,System.Object[])", Scope = "member", Target = "StealFocus.MSBuildExtensions.Tasks.BizTalk.BizTalkCreateHostInstance.#Execute()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Microsoft.Build.Utilities.TaskLoggingHelper.LogMessage(System.String,System.Object[])", Scope = "member", Target = "StealFocus.MSBuildExtensions.Tasks.BizTalk.BizTalkCreateReceiveHandler.#Execute()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Microsoft.Build.Utilities.TaskLoggingHelper.LogMessage(System.String,System.Object[])", Scope = "member", Target = "StealFocus.MSBuildExtensions.Tasks.BizTalk.BizTalkCreateSendHandler.#Execute()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Microsoft.Build.Utilities.TaskLoggingHelper.LogMessage(System.String,System.Object[])", Scope = "member", Target = "StealFocus.MSBuildExtensions.Tasks.BizTalk.BizTalkDeleteAllReceiveHandlers.#Execute()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Microsoft.Build.Utilities.TaskLoggingHelper.LogMessage(System.String,System.Object[])", Scope = "member", Target = "StealFocus.MSBuildExtensions.Tasks.BizTalk.BizTalkDeleteAllSendHandlers.#Execute()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Microsoft.Build.Utilities.TaskLoggingHelper.LogMessage(System.String,System.Object[])", Scope = "member", Target = "StealFocus.MSBuildExtensions.Tasks.BizTalk.BizTalkDeleteHost.#Execute()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Microsoft.Build.Utilities.TaskLoggingHelper.LogMessage(System.String,System.Object[])", Scope = "member", Target = "StealFocus.MSBuildExtensions.Tasks.BizTalk.BizTalkDeleteReceiveHandler.#Execute()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Microsoft.Build.Utilities.TaskLoggingHelper.LogMessage(System.String,System.Object[])", Scope = "member", Target = "StealFocus.MSBuildExtensions.Tasks.BizTalk.BizTalkDeleteSendHandler.#Execute()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Microsoft.Build.Utilities.TaskLoggingHelper.LogMessage(System.String,System.Object[])", Scope = "member", Target = "StealFocus.MSBuildExtensions.Tasks.BizTalk.BizTalkDisableAllReceiveLocations.#Execute()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Microsoft.Build.Utilities.TaskLoggingHelper.LogMessage(System.String,System.Object[])", Scope = "member", Target = "StealFocus.MSBuildExtensions.Tasks.BizTalk.BizTalkDisableReceiveLocations.#Execute()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Microsoft.Build.Utilities.TaskLoggingHelper.LogMessage(System.String,System.Object[])", Scope = "member", Target = "StealFocus.MSBuildExtensions.Tasks.BizTalk.BizTalkEnableAllReceiveLocations.#Execute()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Microsoft.Build.Utilities.TaskLoggingHelper.LogMessage(System.String,System.Object[])", Scope = "member", Target = "StealFocus.MSBuildExtensions.Tasks.BizTalk.BizTalkEnableReceiveLocations.#Execute()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Microsoft.Build.Utilities.TaskLoggingHelper.LogMessage(System.String,System.Object[])", Scope = "member", Target = "StealFocus.MSBuildExtensions.Tasks.BizTalk.BizTalkRemoveApplication.#Execute()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Microsoft.Build.Utilities.TaskLoggingHelper.LogMessage(System.String,System.Object[])", Scope = "member", Target = "StealFocus.MSBuildExtensions.Tasks.BizTalk.BizTalkStartAllOrchestrations.#Execute()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Microsoft.Build.Utilities.TaskLoggingHelper.LogMessage(System.String,System.Object[])", Scope = "member", Target = "StealFocus.MSBuildExtensions.Tasks.BizTalk.BizTalkStartAllSendPorts.#Execute()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Microsoft.Build.Utilities.TaskLoggingHelper.LogMessage(System.String,System.Object[])", Scope = "member", Target = "StealFocus.MSBuildExtensions.Tasks.BizTalk.BizTalkStartApplication.#Execute()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Microsoft.Build.Utilities.TaskLoggingHelper.LogMessage(System.String,System.Object[])", Scope = "member", Target = "StealFocus.MSBuildExtensions.Tasks.BizTalk.BizTalkStartHost.#Execute()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Microsoft.Build.Utilities.TaskLoggingHelper.LogMessage(System.String,System.Object[])", Scope = "member", Target = "StealFocus.MSBuildExtensions.Tasks.BizTalk.BizTalkStartOrchestrations.#Execute()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Microsoft.Build.Utilities.TaskLoggingHelper.LogMessage(System.String,System.Object[])", Scope = "member", Target = "StealFocus.MSBuildExtensions.Tasks.BizTalk.BizTalkStartSendPorts.#Execute()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Microsoft.Build.Utilities.TaskLoggingHelper.LogMessage(System.String,System.Object[])", Scope = "member", Target = "StealFocus.MSBuildExtensions.Tasks.BizTalk.BizTalkStopAllSendPorts.#Execute()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Microsoft.Build.Utilities.TaskLoggingHelper.LogMessage(System.String,System.Object[])", Scope = "member", Target = "StealFocus.MSBuildExtensions.Tasks.BizTalk.BizTalkStopApplication.#Execute()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Microsoft.Build.Utilities.TaskLoggingHelper.LogMessage(System.String,System.Object[])", Scope = "member", Target = "StealFocus.MSBuildExtensions.Tasks.BizTalk.BizTalkStopHost.#Execute()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Microsoft.Build.Utilities.TaskLoggingHelper.LogMessage(System.String,System.Object[])", Scope = "member", Target = "StealFocus.MSBuildExtensions.Tasks.BizTalk.BizTalkStopSendPorts.#Execute()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Microsoft.Build.Utilities.TaskLoggingHelper.LogMessage(System.String,System.Object[])", Scope = "member", Target = "StealFocus.MSBuildExtensions.Tasks.BizTalk.BizTalkTerminateAllOrchestrations.#Execute()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1711:IdentifiersShouldNotHaveIncorrectSuffix", Scope = "type", Target = "StealFocus.MSBuildExtensions.Tasks.BizTalk.BizTalkCleanHostQueue")]
